name: regex_energy_experiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - pandas
  - numpy
  - matplotlib
  - pip
  - pip:
    - python-dotenv
    - requests
    - -e ../pyEnergiBridge