name: regex_energy_experiment_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.3
  - scipy=1.15.2
  - seaborn=0.13.2
  - numpy
  - matplotlib=3.10.0
  - pip
  - pip:
    - python-dotenv
    - requests